# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend-config
#   namespace: expense
# data:
#   DB_HOST: mysql-service # mysql component service name


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1.0
        # envFrom:
        # - configMapRef:
        #     name: frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: expense
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  selector:
    component: frontend
    project: expense
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer